# Site settings for ba-gmbg.ch project
title: BA-GMBG.CH
email: arlind@incodeks.com  # Update this with your email
description: >- 
  This is the official website for BA-GMBG.CH.
baseurl: "construct-org-ch/ba-gmbh.ch.git"  # Leave empty if your site is hosted at the root domain
url: "http://construct-org-ch.github.io/"  # Update this when you deploy your site

# Social media usernames (optional)
twitter_username: your_twitter_handle  # Update this
github_username: arlindkerqeli  # Update this

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Directories or files to exclude from processing
# Exclude anything that is unnecessary to reduce build time
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
